### ISSUE TITLE
メモリ不足警告時にクラッシュ

### ISSUE THREAD

**Issue by ktysne** [szk-atmosphere/URLEmbeddedView#6]
初めまして。
大変素晴らしいライブラリだと思い触らせていただきました。
表題の状況におきましてCrashlyticsに以下のログを出力しクラッシュいたしましたので、ご報告させていただきます。

> CRASH_INFO_ENTRY_1
abort() called
CRASH_INFO_ENTRY_0
Unrecognized selector -[URLEmbeddedView.OGImageCacheManager didReceiveMemoryWarning:]

iOSシミュレータにてメモリ不足警告のシミュレートを行うことでも再現可能でした。
問題の発生は以下の環境で確認いたしました。

- iPhone 6 / 9.0.2
- iOSシミュレータ / 9.2

ご参考になればと思います。
よろしくお願いいたします。

**Comment by ktysne** [comment]
問題が解決されていることを確認いたしました。
素早いご対応ありがとうございました。

**Comment by szk-atmosphere** [comment]
CocoaPodsもリリースしましたので、もしよければそちらからも。
i've released 0.3.2 at cocoapods, please try it.
