### ISSUE TITLE
Require Objective C Version

### ISSUE THREAD

**Issue by parthpatel1105** [szk-atmosphere/URLEmbeddedView#8]
I need this same code for Objective C

**Comment by szk-atmosphere** [comment]
You can call swift code from Objective-C.

**Comment by parthpatel1105** [comment]
OK Thank you.

**Comment by szk-atmosphere** [comment]
This is Objective-C sample.
[https://github.com/szk-atmosphere/URLEmbeddedView/blob/master/URLEmbeddedViewSample/URLEmbeddedViewSample/OGObjcSampleViewController.m](https://github.com/szk-atmosphere/URLEmbeddedView/blob/master/URLEmbeddedViewSample/URLEmbeddedViewSample/OGObjcSampleViewController.m)

**Comment by parthpatel1105** [comment]
Thank you so much.

On Wed, Mar 30, 2016 at 9:28 PM, Taiki Suzuki <notifications@github.com>
wrote:

> This is Objective-C sample.
>
> https://github.com/szk-atmosphere/URLEmbeddedView/blob/master/URLEmbeddedViewSample/URLEmbeddedViewSample/OGObjcSampleViewController.m
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/szk-atmosphere/URLEmbeddedView/issues/8#issuecomment-203502038>
>



-- 

Thanks,
Best Regards,
*Parth Patel*
+91 9925053715,
