### ISSUE TITLE
pod fixes

### ISSUE THREAD

**Issue by Abhishek9634** [szk-atmosphere/URLEmbeddedView#89]
Please update your podspec to add dependency for  
``` 
'MisterFusion' 
'NoticeObserveKit'
```
as of now in your sample, I have to specify in podfile in order to work

**Comment by marty-suzuki** [comment]
This example is  independent from Cocoapods. Instead it depends on Carthage.
You can use those frameworks with executing  `carthage update` command at `/URLEmbeddedView/Example`.
